---
deployment:
  tasks:
    - export DEPLOYPATH=~/public_html/
    - cp -R templates $DEPLOYPATH
    - cp -R administrator $DEPLOYPATH
    - cp -R language $DEPLOYPATH
    - cp ~/src/configuration.php $DEPLOYPATH
